/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "oc_collection.h"
#include "oc_log.h"

/*
 * JNI function calls require different calling conventions for C and C++. These JCALL macros are used so
 * that the same typemaps can be used for generating code for both C and C++. These macros are originaly from
 * the SWIG javahead.swg. They placed here because the SWIG preprocessor does not expand macros that are
 * within the SWIG header code insertion blocks.
 */
#ifdef __cplusplus
#   define JCALL0(func, jenv) jenv->func()
#   define JCALL1(func, jenv, ar1) jenv->func(ar1)
#   define JCALL2(func, jenv, ar1, ar2) jenv->func(ar1, ar2)
#   define JCALL3(func, jenv, ar1, ar2, ar3) jenv->func(ar1, ar2, ar3)
#   define JCALL4(func, jenv, ar1, ar2, ar3, ar4) jenv->func(ar1, ar2, ar3, ar4)
#   define JCALL5(func, jenv, ar1, ar2, ar3, ar4, ar5) jenv->func(ar1, ar2, ar3, ar4, ar5)
#   define JCALL6(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6)
#   define JCALL7(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6, ar7)
#   define JCALL9(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9)
#else
#   define JCALL0(func, jenv) (*jenv)->func(jenv)
#   define JCALL1(func, jenv, ar1) (*jenv)->func(jenv, ar1)
#   define JCALL2(func, jenv, ar1, ar2) (*jenv)->func(jenv, ar1, ar2)
#   define JCALL3(func, jenv, ar1, ar2, ar3) (*jenv)->func(jenv, ar1, ar2, ar3)
#   define JCALL4(func, jenv, ar1, ar2, ar3, ar4) (*jenv)->func(jenv, ar1, ar2, ar3, ar4)
#   define JCALL5(func, jenv, ar1, ar2, ar3, ar4, ar5) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5)
#   define JCALL6(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6)
#   define JCALL7(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7)
#   define JCALL9(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9)
#endif

/*
 * This struct used to hold information needed for java callbacks.
 * When registering a callback handler from java the `JNIEnv`
 * and the java callback handler object must be stored so they
 * can later be used when the callback comes from C this is
 * the `jcb_obj`.
 *
 * If the function used to register the callback also accepts
 * user_data in the form of a void* the `jni_callback_data`
 * can be passed up to the C layer so it can be used in the
 * callback function.
 *
 * The `juser_data` is used to hold a java object that is passed
 * in when registering a callback handler. This value can then be
 * passed back upto the java callback class. Serving the same
 * function as the C void *user_data pointer.
 */
typedef struct jni_callback_data_s {
  struct jni_callback_data_s *next;
  JNIEnv *jenv;
  jobject jcb_obj;
  jobject juser_data;
} jni_callback_data;

/*
 * Container used to hold all `jni_callback_data` that is
 * allocated dynamically. This can be used to find the
 * memory allocated for the `jni_callback_data` if the callback
 * is removed or unregistered. This can all so be used to clean
 * up the allocated memory when shutting down the stack.
 */
OC_LIST(jni_callbacks);

#define JNI_CURRENT_VERSION JNI_VERSION_1_6

static JavaVM *jvm;

static JNIEnv* GetJNIEnv(jint* getEnvResult)
{
    JNIEnv *env = NULL;
    *getEnvResult = JCALL2(GetEnv, jvm, (void**)&env, JNI_CURRENT_VERSION);
    switch (*getEnvResult)
    {
        case JNI_OK:
            return env;
        case JNI_EDETACHED:
#    ifdef __ANDROID__
            if(JCALL2(AttachCurrentThread, jvm, &env, NULL) < 0)
#    else
            if(JCALL2(AttachCurrentThread, jvm, (void**)&env, NULL) < 0)
#    endif
            {
                OC_DBG("Failed to get the environment");
                return NULL;
            }
            else
            {
                return env;
            }
        case JNI_EVERSION:
            OC_DBG("JNI version not supported");
            break;
        default:
            OC_DBG("Failed to get the environment");
            return NULL;
    }
    return NULL;
}

static void ReleaseJNIEnv(jint getEnvResult) {
    if (JNI_EDETACHED == getEnvResult) {
        JCALL0(DetachCurrentThread, jvm);
    }
}


#include "oc_collection.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1next_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  struct oc_link_s *arg2 = (struct oc_link_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  arg2 = *(struct oc_link_s **)&jarg2; 
  if (arg1) (arg1)->next = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  struct oc_link_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  result = (struct oc_link_s *) ((arg1)->next);
  *(struct oc_link_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1resource_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_resource_t *arg2 = (oc_resource_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  arg2 = *(oc_resource_t **)&jarg2; 
  if (arg1) (arg1)->resource = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1resource_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_resource_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  result = (oc_resource_t *) ((arg1)->resource);
  *(oc_resource_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1ins_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_string_t arg2 ;
  char const *temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  temp2 = 0;
  (&arg2)->ptr = 0;
  if (jarg2) {
    temp2 = (*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    oc_new_string(&arg2, temp2, (*jenv)->GetStringUTFLength(jenv, jarg2));
    if (!(&arg2)->ptr) {
      return ;
    }
  }
  if (arg1) (arg1)->ins = arg2;
  
  if ((&arg2)->ptr) {
    (*jenv)->ReleaseStringUTFChars(jenv, jarg2, temp2);
  }
}


SWIGEXPORT jstring JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1ins_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_string_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  result =  ((arg1)->ins);
  if (&result) {
    jresult = (*jenv)->NewStringUTF(jenv, (const char *)oc_string(result));
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1rel_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2) {
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_string_array_t arg2 ;
  jint jsize2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  {
    int i = 0;
    if (jarg2) {
      jsize2 = (*jenv)->GetArrayLength(jenv, jarg2);
      oc_new_string_array(&arg2, jsize2);
      for (i = 0; i<jsize2; i++) {
        jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg2, i);
        const char *c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
        oc_string_array_add_item(arg2, c_string);
        (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
        (*jenv)->DeleteLocalRef(jenv, j_string);
      }
    } else {
      (&arg2)->ptr = 0;
      (&arg2)->size = 0;
      jsize2 = 0;
    }
  }
  if (arg1) (arg1)->rel = arg2;
  
}


SWIGEXPORT jobjectArray JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCLink_1rel_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  oc_string_array_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_link_s **)&jarg1; 
  result =  ((arg1)->rel);
  {
    if ((&result)->ptr) {
      int i;
      jsize len=0;
      jstring temp_string;
      const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
      len = (jsize)oc_string_array_get_allocated_size(result);
      jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
      /* exception checking omitted */
      
      for (i=0; i<len; i++) {
        //temp_string = JCALL1(NewStringUTF, jenv, *result++);
        temp_string = (*jenv)->NewStringUTF(jenv, oc_string_array_get_item(result, i));
        (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
        (*jenv)->DeleteLocalRef(jenv, temp_string);
      }
    }
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_new_1OCLink(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct oc_link_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct oc_link_s *)calloc(1, sizeof(struct oc_link_s));
  *(struct oc_link_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_delete_1OCLink(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct oc_link_s *arg1 = (struct oc_link_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct oc_link_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1next_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  struct oc_collection_s *arg2 = (struct oc_collection_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  arg2 = *(struct oc_collection_s **)&jarg2; 
  if (arg1) (arg1)->next = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  struct oc_collection_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result = (struct oc_collection_s *) ((arg1)->next);
  *(struct oc_collection_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1device_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->device = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1device_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result =  ((arg1)->device);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_t arg2 ;
  char const *temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  temp2 = 0;
  (&arg2)->ptr = 0;
  if (jarg2) {
    temp2 = (*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    oc_new_string(&arg2, temp2, (*jenv)->GetStringUTFLength(jenv, jarg2));
    if (!(&arg2)->ptr) {
      return ;
    }
  }
  if (arg1) (arg1)->name = arg2;
  
  if ((&arg2)->ptr) {
    (*jenv)->ReleaseStringUTFChars(jenv, jarg2, temp2);
  }
}


SWIGEXPORT jstring JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result =  ((arg1)->name);
  if (&result) {
    jresult = (*jenv)->NewStringUTF(jenv, (const char *)oc_string(result));
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1uri_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_t arg2 ;
  char const *temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  temp2 = 0;
  (&arg2)->ptr = 0;
  if (jarg2) {
    temp2 = (*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    oc_new_string(&arg2, temp2, (*jenv)->GetStringUTFLength(jenv, jarg2));
    if (!(&arg2)->ptr) {
      return ;
    }
  }
  if (arg1) (arg1)->uri = arg2;
  
  if ((&arg2)->ptr) {
    (*jenv)->ReleaseStringUTFChars(jenv, jarg2, temp2);
  }
}


SWIGEXPORT jstring JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1uri_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result =  ((arg1)->uri);
  if (&result) {
    jresult = (*jenv)->NewStringUTF(jenv, (const char *)oc_string(result));
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1types_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_array_t arg2 ;
  jint jsize2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  {
    int i = 0;
    if (jarg2) {
      jsize2 = (*jenv)->GetArrayLength(jenv, jarg2);
      oc_new_string_array(&arg2, jsize2);
      for (i = 0; i<jsize2; i++) {
        jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg2, i);
        const char *c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
        oc_string_array_add_item(arg2, c_string);
        (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
        (*jenv)->DeleteLocalRef(jenv, j_string);
      }
    } else {
      (&arg2)->ptr = 0;
      (&arg2)->size = 0;
      jsize2 = 0;
    }
  }
  if (arg1) (arg1)->types = arg2;
  
}


SWIGEXPORT jobjectArray JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1types_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_string_array_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result =  ((arg1)->types);
  {
    if ((&result)->ptr) {
      int i;
      jsize len=0;
      jstring temp_string;
      const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
      len = (jsize)oc_string_array_get_allocated_size(result);
      jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
      /* exception checking omitted */
      
      for (i=0; i<len; i++) {
        //temp_string = JCALL1(NewStringUTF, jenv, *result++);
        temp_string = (*jenv)->NewStringUTF(jenv, oc_string_array_get_item(result, i));
        (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
        (*jenv)->DeleteLocalRef(jenv, temp_string);
      }
    }
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1interfaces_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_interface_mask_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  arg2 = (oc_interface_mask_t)jarg2;
  if (arg1) (arg1)->interfaces = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1interfaces_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_interface_mask_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result = (oc_interface_mask_t) ((arg1)->interfaces);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1defaultInterface_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_interface_mask_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  arg2 = (oc_interface_mask_t)jarg2;
  if (arg1) (arg1)->default_interface = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1defaultInterface_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_interface_mask_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result = (oc_interface_mask_t) ((arg1)->default_interface);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1properties_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_resource_properties_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  arg2 = (oc_resource_properties_t)jarg2;
  if (arg1) (arg1)->properties = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCCollectionUtilJNI_OCCollection_1properties_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  oc_resource_properties_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  result =  ((arg1)->properties);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_delete_1OCCollection(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct oc_collection_s *arg1 = (struct oc_collection_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct oc_collection_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jboolean JNICALL Java_org_iotivity_OCCollectionUtilJNI_handleCollectionRequest(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_, jint jarg3) {
  jboolean jresult = 0 ;
  oc_method_t arg1 ;
  oc_request_t *arg2 = (oc_request_t *) 0 ;
  oc_interface_mask_t arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (oc_method_t)jarg1; 
  arg2 = *(oc_request_t **)&jarg2; 
  arg3 = (oc_interface_mask_t)jarg3;
  result = (bool)oc_handle_collection_request(arg1,arg2,arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_newCollection(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  oc_collection_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (oc_collection_t *)oc_collection_alloc();
  *(oc_collection_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_freeCollection(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  oc_collection_t *arg1 = (oc_collection_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_collection_t **)&jarg1; 
  oc_collection_free(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_getCollectionByUri(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  size_t arg3 ;
  oc_collection_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (oc_collection_t *)oc_get_collection_by_uri((char const *)arg1,arg2,arg3);
  *(oc_collection_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_collectionGetAll(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  oc_collection_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (oc_collection_t *)oc_collection_get_all();
  *(oc_collection_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCCollectionUtilJNI_getLinkByUri(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  oc_collection_t *arg1 = (oc_collection_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  oc_link_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_collection_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (oc_link_t *)oc_get_link_by_uri(arg1,(char const *)arg2,arg3);
  *(oc_link_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_iotivity_OCCollectionUtilJNI_checkIfCollection(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  oc_resource_t *arg1 = (oc_resource_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_resource_t **)&jarg1; 
  result = (bool)oc_check_if_collection(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCCollectionUtilJNI_collectionAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  oc_collection_t *arg1 = (oc_collection_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_collection_t **)&jarg1; 
  oc_collection_add(arg1);
}


#ifdef __cplusplus
}
#endif

