/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "oc_collection.h"
#include "oc_log.h"

/*
 * JNI function calls require different calling conventions for C and C++. These JCALL macros are used so
 * that the same typemaps can be used for generating code for both C and C++. These macros are originaly from
 * the SWIG javahead.swg. They placed here because the SWIG preprocessor does not expand macros that are
 * within the SWIG header code insertion blocks.
 */
#ifdef __cplusplus
#   define JCALL0(func, jenv) jenv->func()
#   define JCALL1(func, jenv, ar1) jenv->func(ar1)
#   define JCALL2(func, jenv, ar1, ar2) jenv->func(ar1, ar2)
#   define JCALL3(func, jenv, ar1, ar2, ar3) jenv->func(ar1, ar2, ar3)
#   define JCALL4(func, jenv, ar1, ar2, ar3, ar4) jenv->func(ar1, ar2, ar3, ar4)
#   define JCALL5(func, jenv, ar1, ar2, ar3, ar4, ar5) jenv->func(ar1, ar2, ar3, ar4, ar5)
#   define JCALL6(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6)
#   define JCALL7(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6, ar7)
#   define JCALL9(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9) jenv->func(ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9)
#else
#   define JCALL0(func, jenv) (*jenv)->func(jenv)
#   define JCALL1(func, jenv, ar1) (*jenv)->func(jenv, ar1)
#   define JCALL2(func, jenv, ar1, ar2) (*jenv)->func(jenv, ar1, ar2)
#   define JCALL3(func, jenv, ar1, ar2, ar3) (*jenv)->func(jenv, ar1, ar2, ar3)
#   define JCALL4(func, jenv, ar1, ar2, ar3, ar4) (*jenv)->func(jenv, ar1, ar2, ar3, ar4)
#   define JCALL5(func, jenv, ar1, ar2, ar3, ar4, ar5) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5)
#   define JCALL6(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6)
#   define JCALL7(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7)
#   define JCALL9(func, jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9) (*jenv)->func(jenv, ar1, ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9)
#endif

/*
 * This struct used to hold information needed for java callbacks.
 * When registering a callback handler from java the `JNIEnv`
 * and the java callback handler object must be stored so they
 * can later be used when the callback comes from C this is
 * the `jcb_obj`.
 *
 * If the function used to register the callback also accepts
 * user_data in the form of a void* the `jni_callback_data`
 * can be passed up to the C layer so it can be used in the
 * callback function.
 *
 * The `juser_data` is used to hold a java object that is passed
 * in when registering a callback handler. This value can then be
 * passed back upto the java callback class. Serving the same
 * function as the C void *user_data pointer.
 */
typedef struct jni_callback_data_s {
  struct jni_callback_data_s *next;
  JNIEnv *jenv;
  jobject jcb_obj;
  jobject juser_data;
} jni_callback_data;

/*
 * Container used to hold all `jni_callback_data` that is
 * allocated dynamically. This can be used to find the
 * memory allocated for the `jni_callback_data` if the callback
 * is removed or unregistered. This can all so be used to clean
 * up the allocated memory when shutting down the stack.
 */
OC_LIST(jni_callbacks);

#define JNI_CURRENT_VERSION JNI_VERSION_1_6

static JavaVM *jvm;

static JNIEnv* GetJNIEnv(jint* getEnvResult)
{
    JNIEnv *env = NULL;
    *getEnvResult = JCALL2(GetEnv, jvm, (void**)&env, JNI_CURRENT_VERSION);
    switch (*getEnvResult)
    {
        case JNI_OK:
            return env;
        case JNI_EDETACHED:
#    ifdef __ANDROID__
            if(JCALL2(AttachCurrentThread, jvm, &env, NULL) < 0)
#    else
            if(JCALL2(AttachCurrentThread, jvm, (void**)&env, NULL) < 0)
#    endif
            {
                OC_DBG("Failed to get the environment");
                return NULL;
            }
            else
            {
                return env;
            }
        case JNI_EVERSION:
            OC_DBG("JNI version not supported");
            break;
        default:
            OC_DBG("Failed to get the environment");
            return NULL;
    }
    return NULL;
}

static void ReleaseJNIEnv(jint getEnvResult) {
    if (JNI_EDETACHED == getEnvResult) {
        JCALL0(DetachCurrentThread, jvm);
    }
}


#include "security/oc_acl.h"


#include "oc_obt.h"


void jni_obt_init(void* dummy) {
    oc_obt_init();
}


static void jni_obt_discovery_cb(oc_uuid_t *uuid, oc_endpoint_t *eps, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  assert(user_data);
  jni_callback_data *data = (jni_callback_data *)user_data;
  jint getEnvResult = 0;
  data->jenv = GetJNIEnv(&getEnvResult);
  assert(data->jenv);

  const jclass callbackInterfaceClass = JCALL1(FindClass,
        (data->jenv),
        "org/iotivity/OCObtDiscoveryHandler");
  assert(callbackInterfaceClass);
  const jmethodID mid_handler = JCALL3(GetMethodID,
        (data->jenv),
        callbackInterfaceClass,
        "handler",
        "(Lorg/iotivity/OCUuid;Lorg/iotivity/OCEndpoint;Ljava/lang/Object;)V");
  assert(mid_handler);

  const jclass cls_OCUuid = JCALL1(FindClass, (data->jenv), "org/iotivity/OCUuid");
  assert(cls_OCUuid);
  const jmethodID mid_OCUuid_init = JCALL3(GetMethodID, (data->jenv), cls_OCUuid, "<init>", "(JZ)V");
  assert(mid_OCUuid_init);
  const jclass cls_OCEndpoint = JCALL1(FindClass, (data->jenv), "org/iotivity/OCEndpoint");
  assert(cls_OCEndpoint);
  const jmethodID mid_OCEndpoint_init = JCALL3(GetMethodID,
        (data->jenv),
        cls_OCEndpoint,
        "<init>",
        "(JZ)V");
  assert(mid_OCEndpoint_init);

  /* make copy of uuid that will be owned by Java code */
  oc_uuid_t *juuid = malloc(sizeof(oc_uuid_t));
  memcpy(juuid->id, uuid->id, 16);

  JCALL5(CallVoidMethod,
        (data->jenv),
        data->jcb_obj,
        mid_handler,
        JCALL4(NewObject, (data->jenv), cls_OCUuid, mid_OCUuid_init, (jlong)juuid, true),
        JCALL4(NewObject, (data->jenv), cls_OCEndpoint, mid_OCEndpoint_init, (jlong)eps, false),
        data->juser_data);

  ReleaseJNIEnv(getEnvResult);
}


int jni_oc_obt_discover_unowned_devices0(oc_obt_discovery_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_discover_unowned_devices(callback, jcb);
}


int jni_oc_obt_discover_unowned_devices1(oc_obt_discovery_cb_t callback, jni_callback_data *jcb,
                                          void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_discover_unowned_devices(callback, jcb);
}


int jni_oc_obt_discover_owned_devices0(oc_obt_discovery_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_discover_owned_devices(callback, jcb);
}


int jni_oc_obt_discover_owned_devices1(oc_obt_discovery_cb_t callback, jni_callback_data *jcb,
                                          void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_discover_owned_devices(callback, jcb);
}


static void jni_obt_device_status_cb(oc_uuid_t *uuid, int status, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jni_callback_data *data = (jni_callback_data *)user_data;
  jint getEnvResult = 0;
  data->jenv = GetJNIEnv(&getEnvResult);
  assert(data->jenv);

  const jclass callbackInterfaceClass = JCALL1(FindClass,
        (data->jenv),
        "org/iotivity/OCObtDeviceStatusHandler");
  assert(callbackInterfaceClass);
  const jmethodID mid_handler = JCALL3(GetMethodID,
        (data->jenv),
        callbackInterfaceClass,
        "handler",
        "(Lorg/iotivity/OCUuid;ILjava/lang/Object;)V");
  assert(mid_handler);

  const jclass cls_OCUuid = JCALL1(FindClass, (data->jenv), "org/iotivity/OCUuid");
  assert(cls_OCUuid);
  const jmethodID mid_OCUuid_init = JCALL3(GetMethodID, (data->jenv), cls_OCUuid, "<init>", "(JZ)V");
  assert(mid_OCUuid_init);

  /* make copy of uuid that will be owned by Java code */
  oc_uuid_t *juuid = malloc(sizeof(oc_uuid_t));
  memcpy(juuid->id, uuid->id, 16);

  JCALL5(CallVoidMethod,
        (data->jenv),
        data->jcb_obj,
        mid_handler,
        JCALL4(NewObject, (data->jenv), cls_OCUuid, mid_OCUuid_init, (jlong)juuid, true),
        (jint) status,
        data->juser_data);

  ReleaseJNIEnv(getEnvResult);
}


int jni_obt_perform_just_works_otm0(oc_uuid_t *uuid, oc_obt_device_status_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_perform_just_works_otm(uuid, callback, jcb);
}


int jni_obt_perform_just_works_otm1(oc_uuid_t *uuid, oc_obt_device_status_cb_t callback, jni_callback_data *jcb, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_perform_just_works_otm(uuid, callback, jcb);
}


int jni_obt_device_hard_reset0(oc_uuid_t *uuid, oc_obt_device_status_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_device_hard_reset(uuid, callback, jcb);
}


int jni_obt_device_hard_reset1(oc_uuid_t *uuid, oc_obt_device_status_cb_t callback, jni_callback_data *jcb, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_device_hard_reset(uuid, callback, jcb);
}


static void jni_obt_status_cb(int status, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jni_callback_data *data = (jni_callback_data *)user_data;
  jint getEnvResult = 0;
  data->jenv = GetJNIEnv(&getEnvResult);
  assert(data->jenv);

  const jclass callbackInterfaceClass = JCALL1(FindClass,
        (data->jenv),
        "org/iotivity/OCObtStatusHandler");
  assert(callbackInterfaceClass);
  const jmethodID mid_handler = JCALL3(GetMethodID,
        (data->jenv),
        callbackInterfaceClass,
        "handler",
        "(ILjava/lang/Object;)V");
  assert(mid_handler);

  JCALL4(CallVoidMethod,
        (data->jenv),
        data->jcb_obj,
        mid_handler,
        (jint) status,
        data->juser_data);

  ReleaseJNIEnv(getEnvResult);
}


int jni_obt_provision_pairwise_credentials0(oc_uuid_t *uuid1, oc_uuid_t *uuid2, oc_obt_status_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_provision_pairwise_credentials(uuid1, uuid2, callback, jcb);
}


int jni_obt_provision_pairwise_credentials1(oc_uuid_t *uuid1, oc_uuid_t *uuid2, oc_obt_status_cb_t callback, jni_callback_data *jcb, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_provision_pairwise_credentials(uuid1, uuid2, callback, jcb);
}


int jni_obt_provision_ace0(oc_uuid_t *subject, oc_sec_ace_t *ace, oc_obt_device_status_cb_t callback, jni_callback_data *jcb)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = NULL;
  return oc_obt_provision_ace(subject, ace, callback, jcb);
}


int jni_obt_provision_ace1(oc_uuid_t *subject, oc_sec_ace_t *ace, oc_obt_device_status_cb_t callback, jni_callback_data *jcb, void *user_data)
{
  OC_DBG("JNI: %s\n", __func__);
  jcb->juser_data = *(jobject*)user_data;
  return oc_obt_provision_ace(subject, ace, callback, jcb);
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OC_1ACE_1NO_1WC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  oc_ace_wildcard_t result;
  
  (void)jenv;
  (void)jcls;
  result = (oc_ace_wildcard_t)OC_ACE_NO_WC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OC_1ACE_1WC_1ALL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  oc_ace_wildcard_t result;
  
  (void)jenv;
  (void)jcls;
  result = (oc_ace_wildcard_t)OC_ACE_WC_ALL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OC_1ACE_1WC_1ALL_1SECURED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  oc_ace_wildcard_t result;
  
  (void)jenv;
  (void)jcls;
  result = (oc_ace_wildcard_t)OC_ACE_WC_ALL_SECURED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OC_1ACE_1WC_1ALL_1PUBLIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  oc_ace_wildcard_t result;
  
  (void)jenv;
  (void)jcls;
  result = (oc_ace_wildcard_t)OC_ACE_WC_ALL_PUBLIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OC_1CONN_1AUTH_1CRYPT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  oc_ace_connection_type_t result;
  
  (void)jenv;
  (void)jcls;
  result = (oc_ace_connection_type_t)OC_CONN_AUTH_CRYPT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1next_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  struct oc_ace_res_s *arg2 = (struct oc_ace_res_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  arg2 = *(struct oc_ace_res_s **)&jarg2; 
  if (arg1) (arg1)->next = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  struct oc_ace_res_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  result = (struct oc_ace_res_s *) ((arg1)->next);
  *(struct oc_ace_res_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1href_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_string_t arg2 ;
  char const *temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  temp2 = 0;
  (&arg2)->ptr = 0;
  if (jarg2) {
    temp2 = (*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    oc_new_string(&arg2, temp2, (*jenv)->GetStringUTFLength(jenv, jarg2));
    if (!(&arg2)->ptr) {
      return ;
    }
  }
  if (arg1) (arg1)->href = arg2;
  
  if ((&arg2)->ptr) {
    (*jenv)->ReleaseStringUTFChars(jenv, jarg2, temp2);
  }
}


SWIGEXPORT jstring JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1href_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_string_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  result =  ((arg1)->href);
  if (&result) {
    jresult = (*jenv)->NewStringUTF(jenv, (const char *)oc_string(result));
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1interfaces_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_interface_mask_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  arg2 = (oc_interface_mask_t)jarg2;
  if (arg1) (arg1)->interfaces = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1interfaces_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_interface_mask_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  result =  ((arg1)->interfaces);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1types_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_string_array_t arg2 ;
  jint jsize2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  {
    int i = 0;
    if (jarg2) {
      jsize2 = (*jenv)->GetArrayLength(jenv, jarg2);
      oc_new_string_array(&arg2, jsize2);
      for (i = 0; i<jsize2; i++) {
        jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg2, i);
        const char *c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
        oc_string_array_add_item(arg2, c_string);
        (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
        (*jenv)->DeleteLocalRef(jenv, j_string);
      }
    } else {
      (&arg2)->ptr = 0;
      (&arg2)->size = 0;
      jsize2 = 0;
    }
  }
  if (arg1) (arg1)->types = arg2;
  
}


SWIGEXPORT jobjectArray JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1types_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_string_array_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  result =  ((arg1)->types);
  {
    if ((&result)->ptr) {
      int i;
      jsize len=0;
      jstring temp_string;
      const jclass clazz = (*jenv)->FindClass(jenv, "java/lang/String");
      len = (jsize)oc_string_array_get_allocated_size(result);
      jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
      /* exception checking omitted */
      
      for (i=0; i<len; i++) {
        //temp_string = JCALL1(NewStringUTF, jenv, *result++);
        temp_string = (*jenv)->NewStringUTF(jenv, oc_string_array_get_item(result, i));
        (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
        (*jenv)->DeleteLocalRef(jenv, temp_string);
      }
    }
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1wildcard_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_ace_wildcard_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  arg2 = (oc_ace_wildcard_t)jarg2; 
  if (arg1) (arg1)->wildcard = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OCAceResource_1wildcard_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  oc_ace_wildcard_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  result = (oc_ace_wildcard_t) ((arg1)->wildcard);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_new_1OCAceResource(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct oc_ace_res_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct oc_ace_res_s *)calloc(1, sizeof(struct oc_ace_res_s));
  *(struct oc_ace_res_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_delete_1OCAceResource(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct oc_ace_res_s *arg1 = (struct oc_ace_res_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct oc_ace_res_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCSecurityAce_1next_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct oc_sec_ace_s *arg1 = (struct oc_sec_ace_s *) 0 ;
  struct oc_sec_ace_s *arg2 = (struct oc_sec_ace_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct oc_sec_ace_s **)&jarg1; 
  arg2 = *(struct oc_sec_ace_s **)&jarg2; 
  if (arg1) (arg1)->next = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_OCSecurityAce_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct oc_sec_ace_s *arg1 = (struct oc_sec_ace_s *) 0 ;
  struct oc_sec_ace_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_sec_ace_s **)&jarg1; 
  result = (struct oc_sec_ace_s *) ((arg1)->next);
  *(struct oc_sec_ace_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_OCSecurityAce_1aceid_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct oc_sec_ace_s *arg1 = (struct oc_sec_ace_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_sec_ace_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->aceid = arg2;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_OCSecurityAce_1aceid_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct oc_sec_ace_s *arg1 = (struct oc_sec_ace_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct oc_sec_ace_s **)&jarg1; 
  result = (int) ((arg1)->aceid);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_delete_1OCSecurityAce(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct oc_sec_ace_s *arg1 = (struct oc_sec_ace_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct oc_sec_ace_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_init(JNIEnv *jenv, jclass jcls) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  {
    (*jenv)->GetJavaVM(jenv, &jvm);
  }
  jni_obt_init(arg1);
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_discoverUnownedDevices_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jobject jarg1) {
  jint jresult = 0 ;
  oc_obt_discovery_cb_t arg1 = (oc_obt_discovery_cb_t) 0 ;
  jni_callback_data *arg2 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg1);
    (*jenv)->DeleteLocalRef(jenv, jarg1);
    oc_list_add(jni_callbacks, user_data);
    arg1 = jni_obt_discovery_cb;
    arg2 = user_data;
  }
  result = (int)jni_oc_obt_discover_unowned_devices0(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_discoverUnownedDevices_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jobject jarg1, jobject jarg3) {
  jint jresult = 0 ;
  oc_obt_discovery_cb_t arg1 = (oc_obt_discovery_cb_t) 0 ;
  jni_callback_data *arg2 = (jni_callback_data *) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg1);
    (*jenv)->DeleteLocalRef(jenv, jarg1);
    oc_list_add(jni_callbacks, user_data);
    arg1 = jni_obt_discovery_cb;
    arg2 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    arg3 = (void*)&juser_data;
  }
  result = (int)jni_oc_obt_discover_unowned_devices1(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_discoverOwnedDevices_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jobject jarg1) {
  jint jresult = 0 ;
  oc_obt_discovery_cb_t arg1 = (oc_obt_discovery_cb_t) 0 ;
  jni_callback_data *arg2 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg1);
    (*jenv)->DeleteLocalRef(jenv, jarg1);
    oc_list_add(jni_callbacks, user_data);
    arg1 = jni_obt_discovery_cb;
    arg2 = user_data;
  }
  result = (int)jni_oc_obt_discover_owned_devices0(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_discoverOwnedDevices_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jobject jarg1, jobject jarg3) {
  jint jresult = 0 ;
  oc_obt_discovery_cb_t arg1 = (oc_obt_discovery_cb_t) 0 ;
  jni_callback_data *arg2 = (jni_callback_data *) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg1);
    (*jenv)->DeleteLocalRef(jenv, jarg1);
    oc_list_add(jni_callbacks, user_data);
    arg1 = jni_obt_discovery_cb;
    arg2 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    arg3 = (void*)&juser_data;
  }
  result = (int)jni_oc_obt_discover_owned_devices1(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_performJustWorksOtm_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_obt_device_status_cb_t arg2 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg3 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg2);
    (*jenv)->DeleteLocalRef(jenv, jarg2);
    oc_list_add(jni_callbacks, user_data);
    arg2 = jni_obt_device_status_cb;
    arg3 = user_data;
  }
  result = (int)jni_obt_perform_just_works_otm0(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_performJustWorksOtm_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2, jobject jarg4) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_obt_device_status_cb_t arg2 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg3 = (jni_callback_data *) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg2);
    (*jenv)->DeleteLocalRef(jenv, jarg2);
    oc_list_add(jni_callbacks, user_data);
    arg2 = jni_obt_device_status_cb;
    arg3 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg4);
    (*jenv)->DeleteLocalRef(jenv, jarg4);
    arg4 = (void*)&juser_data;
  }
  result = (int)jni_obt_perform_just_works_otm1(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_deviceHardReset_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_obt_device_status_cb_t arg2 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg3 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg2);
    (*jenv)->DeleteLocalRef(jenv, jarg2);
    oc_list_add(jni_callbacks, user_data);
    arg2 = jni_obt_device_status_cb;
    arg3 = user_data;
  }
  result = (int)jni_obt_device_hard_reset0(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_deviceHardReset_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2, jobject jarg4) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_obt_device_status_cb_t arg2 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg3 = (jni_callback_data *) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg2);
    (*jenv)->DeleteLocalRef(jenv, jarg2);
    oc_list_add(jni_callbacks, user_data);
    arg2 = jni_obt_device_status_cb;
    arg3 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg4);
    (*jenv)->DeleteLocalRef(jenv, jarg4);
    arg4 = (void*)&juser_data;
  }
  result = (int)jni_obt_device_hard_reset1(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_provisionPairwiseCredentials_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jobject jarg3) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_uuid_t *arg2 = (oc_uuid_t *) 0 ;
  oc_obt_status_cb_t arg3 = (oc_obt_status_cb_t) 0 ;
  jni_callback_data *arg4 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  arg2 = *(oc_uuid_t **)&jarg2; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    oc_list_add(jni_callbacks, user_data);
    arg3 = jni_obt_status_cb;
    arg4 = user_data;
  }
  result = (int)jni_obt_provision_pairwise_credentials0(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_provisionPairwiseCredentials_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jobject jarg3, jobject jarg5) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_uuid_t *arg2 = (oc_uuid_t *) 0 ;
  oc_obt_status_cb_t arg3 = (oc_obt_status_cb_t) 0 ;
  jni_callback_data *arg4 = (jni_callback_data *) 0 ;
  void *arg5 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  arg2 = *(oc_uuid_t **)&jarg2; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    oc_list_add(jni_callbacks, user_data);
    arg3 = jni_obt_status_cb;
    arg4 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg5);
    (*jenv)->DeleteLocalRef(jenv, jarg5);
    arg5 = (void*)&juser_data;
  }
  result = (int)jni_obt_provision_pairwise_credentials1(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_provisionAce_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jobject jarg3) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_sec_ace_t *arg2 = (oc_sec_ace_t *) 0 ;
  oc_obt_device_status_cb_t arg3 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg4 = (jni_callback_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  arg2 = *(oc_sec_ace_t **)&jarg2; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    oc_list_add(jni_callbacks, user_data);
    arg3 = jni_obt_device_status_cb;
    arg4 = user_data;
  }
  result = (int)jni_obt_provision_ace0(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_iotivity_OCObtJNI_provisionAce_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jobject jarg3, jobject jarg5) {
  jint jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_sec_ace_t *arg2 = (oc_sec_ace_t *) 0 ;
  oc_obt_device_status_cb_t arg3 = (oc_obt_device_status_cb_t) 0 ;
  jni_callback_data *arg4 = (jni_callback_data *) 0 ;
  void *arg5 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  arg2 = *(oc_sec_ace_t **)&jarg2; 
  {
    jni_callback_data *user_data = (jni_callback_data *)malloc(sizeof *user_data);
    user_data->jenv = jenv;
    user_data->jcb_obj = (*jenv)->NewGlobalRef(jenv, jarg3);
    (*jenv)->DeleteLocalRef(jenv, jarg3);
    oc_list_add(jni_callbacks, user_data);
    arg3 = jni_obt_device_status_cb;
    arg4 = user_data;
  }
  {
    jobject juser_data = (*jenv)->NewGlobalRef(jenv, jarg5);
    (*jenv)->DeleteLocalRef(jenv, jarg5);
    arg5 = (void*)&juser_data;
  }
  result = (int)jni_obt_provision_ace1(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_newAceForSubject(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  oc_uuid_t *arg1 = (oc_uuid_t *) 0 ;
  oc_sec_ace_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_uuid_t **)&jarg1; 
  result = (oc_sec_ace_t *)oc_obt_new_ace_for_subject(arg1);
  *(oc_sec_ace_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_newAceForConnection(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  oc_ace_connection_type_t arg1 ;
  oc_sec_ace_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (oc_ace_connection_type_t)jarg1; 
  result = (oc_sec_ace_t *)oc_obt_new_ace_for_connection(arg1);
  *(oc_sec_ace_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_iotivity_OCObtJNI_aceNewResource(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  oc_sec_ace_t *arg1 = (oc_sec_ace_t *) 0 ;
  oc_ace_res_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_sec_ace_t **)&jarg1; 
  result = (oc_ace_res_t *)oc_obt_ace_new_resource(arg1);
  *(oc_ace_res_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceResourceSetHref(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  oc_ace_res_t *arg1 = (oc_ace_res_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_ace_res_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  oc_obt_ace_resource_set_href(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceResoruceSetNumRt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  oc_ace_res_t *arg1 = (oc_ace_res_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_ace_res_t **)&jarg1; 
  arg2 = (int)jarg2; 
  oc_obt_ace_resource_set_num_rt(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceResoruceBindRt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  oc_ace_res_t *arg1 = (oc_ace_res_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_ace_res_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  oc_obt_ace_resource_bind_rt(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceResourceBindIf(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  oc_ace_res_t *arg1 = (oc_ace_res_t *) 0 ;
  oc_interface_mask_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_ace_res_t **)&jarg1; 
  arg2 = (oc_interface_mask_t)jarg2;
  oc_obt_ace_resource_bind_if(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceResourceSetWc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  oc_ace_res_t *arg1 = (oc_ace_res_t *) 0 ;
  oc_ace_wildcard_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_ace_res_t **)&jarg1; 
  arg2 = (oc_ace_wildcard_t)jarg2; 
  oc_obt_ace_resource_set_wc(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_aceAddPermission(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  oc_sec_ace_t *arg1 = (oc_sec_ace_t *) 0 ;
  oc_ace_permissions_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_sec_ace_t **)&jarg1; 
  arg2 = (oc_ace_permissions_t)jarg2;
  oc_obt_ace_add_permission(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_iotivity_OCObtJNI_freeAce(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  oc_sec_ace_t *arg1 = (oc_sec_ace_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(oc_sec_ace_t **)&jarg1; 
  oc_obt_free_ace(arg1);
}


#ifdef __cplusplus
}
#endif

